from enum import Enum


class idProductos(Enum):
    SMARTPHONE_XIAOMI = 0
    LAPTOP_HP = 1
    TECLADO_MICROSOFT = 2
    DISCO_DURO_SEAGATE = 3
    AUDIFONOS_SONY = 4
    CAMARA_CANON = 5
    MONITOR_SAMSUNG = 6
    TABLET_AMAZON_FIRE = 7
    IMPRESORA_EPSON = 8
    SMARTWATCH_SAMSUNG = 9
    MOUSE_LOGITECH = 10